# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: matrogersmtl.com
description: > # this means to ignore newlines until "baseurl:"
  Data science, deep learning, number theory
repository: https://github.com/matrogersmtl/matrogersmtl.github.io
baseurl: ""  # the subpath of your site, e.g. /blog
url: www.matrogersmtl.com  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Mathew Rogers
email: mathewrogers@gmail.com

navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog

social:
  - service: linkedin
    username: rogersmontreal
    link: https://ca.linkedin.com/in/rogersmontreal
  - service: github
    username: matrogersmtl
    link: https://github.com/matrogersmtl
#  - service: twitter
#    username: matrogersmtl
#    link: https://twitter.com/matrogersmtl
#  - service: instagram
#    username: matrogersmtl
#    link: https://instagram.com/matrogersmtl
#  - service: facebook
#    username: matrogersmtl
#    link: https://facebook.com/matrogersmtl


